openapi: 3.0.0
info:
  title: XSS test
  description: "<form action='javascript:alert(\"XSS\")' method='post'><button type='submit' onmousedown=confirm``>Submit</button></form>"
  version: 1.0.0
paths: {}
